#! /usr/bin/env ruby

%w(LICENSE Makefile *.json *.less *.md *.markdown).each do |entry|
  puts "Removing #{entry}..."
  `find ./app/assets/{javascripts,stylesheets}/bower/bower_components -name '#{entry}' | xargs rm`
  `find ./vendor/assets/{javascripts,stylesheets}/bower/bower_components -name '#{entry}' | xargs rm`
end
puts ""
puts "Done, assets should compile now"
